/* Drift Calc — backtest module.
   Loaded by index.html as a separate file so the page stays maintainable.
   Depends on targetsRaw(), CLASSES and renderAll() from the main script,
   all of which exist by the time this runs. Reads returns.json, which is
   generated by build-returns.mjs. If that file isn't there, this section
   explains itself and nothing else on the page is affected. */
(function(){
'use strict';

/* ---------- inject the section after the planning tools ---------- */
const s5 = document.getElementById('s5');
if(!s5 || !s5.parentNode) return;
const sec = document.createElement('section');
sec.id = 's6';
sec.innerHTML =
  '<div class="sec-head"><span class="step-n">+</span><h2>Backtest</h2>' +
  '<span class="sub">What your target mix would have done, using real history instead of a flat guess.</span></div>' +
  '<div class="card"><div id="btBody"></div></div>';
s5.parentNode.insertBefore(sec, s5.nextSibling);

/* ============================ BACKTEST ============================
   Monthly total returns live in returns.json, built by build-returns.mjs from
   the Ken French Data Library and FRED. Index returns, no fees or taxes.
   The file is optional: if it isn't there, this whole section explains itself
   and nothing else on the page cares. */

let RET = null;                 /* {months:[...], series:{US:[],...}} */
let BT = { start:null, rebal:'annual', real:false };

/* Which historical series stands in for each of our asset classes.
   EM and international small value have no free long history, so they ride
   along with developed international. The UI says so out loud. */
const BT_PROXY = { US:'US', USSCV:'USSCV', INTL:'INTL', EM:'INTL', INTLSCV:'INTL', BOND:'BOND' };

function btWeights(){
  const t = targetsRaw();
  const w = {}; let known = 0, unknown = 0;
  for(const c in t){
    const v = +t[c] || 0;
    if(v <= 0) continue;
    if(BT_PROXY[c]){ w[BT_PROXY[c]] = (w[BT_PROXY[c]] || 0) + v; known += v; }
    else unknown += v;              /* custom sleeves: gold, REITs, crypto... */
  }
  if(known > 0) for(const k in w) w[k] = w[k] / known;   /* renormalise */
  return { w, unknown };
}

/* Run one portfolio through the months. Returns the equity curve and stats. */
function btRun(w, from, to, rebal){
  const M = RET.months, S_ = RET.series;
  const keys = Object.keys(w).filter(k => w[k] > 0);
  let val = 1, hold = {};
  keys.forEach(k => hold[k] = w[k]);
  const curve = [], byYear = {};
  let peak = 1, maxDD = 0;

  for(let i = from; i <= to; i++){
    /* a month is only usable if every sleeve we hold has data for it */
    if(keys.some(k => S_[k][i] == null)) continue;
    let nv = 0;
    keys.forEach(k => { hold[k] *= (1 + S_[k][i]); nv += hold[k]; });
    const prev = val; val = nv;

    const yr = M[i].slice(0,4);
    byYear[yr] = (byYear[yr] == null ? 1 : byYear[yr]) * (val / prev);

    if(val > peak) peak = val;
    const dd = val / peak - 1;
    if(dd < maxDD) maxDD = dd;
    curve.push({ m: M[i], v: val });

    const isYearEnd = M[i].slice(4) === '12';
    if(rebal === 'annual' ? isYearEnd : rebal === 'monthly')
      keys.forEach(k => hold[k] = val * w[k]);
  }
  return { curve, val, maxDD, byYear };
}

function btCagr(v, months){ return months > 0 ? Math.pow(v, 12/months) - 1 : 0; }

function renderBacktest(){
  const el = document.getElementById('btBody'); if(!el) return;

  if(RET === 'missing'){
    el.innerHTML = `<div style="font-size:13.5px;color:var(--muted);line-height:1.7">
      The backtest needs <code>returns.json</code>, which isn't loaded. It's built from the
      Ken French Data Library and FRED by the <code>build-returns.mjs</code> script in the
      repo. Everything else on this page works without it.</div>`;
    return;
  }
  if(!RET){ el.innerHTML = `<div style="font-size:13.5px;color:var(--faint)">Loading history…</div>`; return; }

  const { w, unknown } = btWeights();
  const keys = Object.keys(w).filter(k => w[k] > 0);
  if(!keys.length){ el.innerHTML = `<div style="font-size:13.5px;color:var(--muted)">Set a target allocation first and this will fill in.</div>`; return; }

  const M = RET.months, S_ = RET.series;
  /* earliest month where every sleeve in THIS mix has data */
  let earliest = 0;
  for(let i = 0; i < M.length; i++){
    if(keys.every(k => S_[k][i] != null)){ earliest = i; break; }
  }
  const startIdx = BT.start ? Math.max(earliest, M.indexOf(BT.start)) : earliest;
  const endIdx = M.length - 1;
  if(startIdx < 0 || endIdx - startIdx < 12){
    el.innerHTML = `<div style="font-size:13.5px;color:var(--muted)">Not enough history for that combination.</div>`;
    return;
  }

  const mine = btRun(w, startIdx, endIdx, BT.rebal);
  const nMonths = mine.curve.length;
  if(!nMonths){ el.innerHTML = `<div style="font-size:13.5px;color:var(--muted)">No overlapping history for that mix.</div>`; return; }

  /* inflation over the same window, for real returns */
  let infl = 1, inflMonths = 0;
  for(let i = startIdx; i <= endIdx; i++) if(S_.CPI[i] != null){ infl *= (1 + S_.CPI[i]); inflMonths++; }

  const bench = {
    'All US stock': btRun({US:1}, startIdx, endIdx, BT.rebal),
    '60/40 US': btRun({US:0.6, BOND:0.4}, startIdx, endIdx, BT.rebal),
  };
  const noRebal = btRun(w, startIdx, endIdx, 'none');

  const cagr = btCagr(mine.val, nMonths);
  const realCagr = inflMonths ? (1 + cagr) / Math.pow(infl, 12/inflMonths) - 1 : null;
  const years = Object.keys(mine.byYear).filter(y => {
    /* only count calendar years we saw all 12 months of */
    let n = 0; M.forEach((m,i) => { if(m.slice(0,4)===y && i>=startIdx && i<=endIdx) n++; });
    return n === 12;
  });
  const yv = years.map(y => ({ y, r: mine.byYear[y] - 1 })).sort((a,b) => a.r - b.r);
  const worst = yv[0], best = yv[yv.length-1];
  const downYears = yv.filter(x => x.r < 0).length;

  const pct = x => (x*100).toFixed(1) + '%';
  const money = x => '$' + Math.round(x).toLocaleString();
  const START$ = 10000;

  /* sparkline of the equity curve, log scale so early years stay visible */
  const c = mine.curve, W = 640, H = 130;
  const lo = Math.log(Math.min(...c.map(p=>p.v))), hi = Math.log(Math.max(...c.map(p=>p.v)));
  const pts = c.map((p,i) =>
    (i/(c.length-1)*W).toFixed(1) + ',' + (H - (Math.log(p.v)-lo)/((hi-lo)||1)*(H-8) - 4).toFixed(1)
  ).join(' ');

  const mixRows = keys.sort((a,b)=>w[b]-w[a]).map(k =>
    `<span style="display:inline-block;margin-right:14px"><span class="cls-dot" style="background:${(CLASSES[k]||{}).color||'#888'}"></span>${({US:'US',USSCV:'US small value',INTL:'International',BOND:'Bonds'})[k]||k} ${Math.round(w[k]*100)}%</span>`
  ).join('');

  const startOpts = [M[earliest], '199001','200001','201001','201501','202001']
    .filter((v,i,a) => a.indexOf(v)===i && M.indexOf(v) >= earliest)
    .map(v => `<option value="${v}"${v===M[startIdx]?' selected':''}>${v.slice(0,4)}</option>`).join('');

  el.innerHTML = `
    <div style="font-size:13.5px;color:var(--muted);margin-bottom:14px">Your target mix, run through real monthly history. ${mixRows}</div>

    <div style="display:flex;gap:18px;flex-wrap:wrap;align-items:center;margin-bottom:18px;font-size:13px">
      <label>Start <select onchange="btSet('start',this.value)" style="margin-left:6px">${startOpts}</select></label>
      <label>Rebalance
        <select onchange="btSet('rebal',this.value)" style="margin-left:6px">
          <option value="annual"${BT.rebal==='annual'?' selected':''}>Once a year</option>
          <option value="monthly"${BT.rebal==='monthly'?' selected':''}>Every month</option>
          <option value="none"${BT.rebal==='none'?' selected':''}>Never</option>
        </select></label>
      <span style="color:var(--faint)">${M[startIdx].slice(0,4)}–${M[endIdx].slice(0,4)}, ${(nMonths/12).toFixed(0)} years</span>
    </div>

    <div class="stat-strip" style="margin-bottom:18px">
      <div class="stat"><div class="k">$10,000 became</div><div class="v num">${money(START$*mine.val)}</div></div>
      <div class="stat"><div class="k">Return a year</div><div class="v num">${pct(cagr)}</div></div>
      <div class="stat"><div class="k">After inflation</div><div class="v num">${realCagr==null?'—':pct(realCagr)}</div></div>
      <div class="stat"><div class="k">Worst drop</div><div class="v num" style="color:var(--red)">${pct(mine.maxDD)}</div></div>
    </div>

    <svg viewBox="0 0 ${W} ${H}" style="width:100%;height:130px;display:block;margin-bottom:6px" preserveAspectRatio="none">
      <polyline points="${pts}" fill="none" stroke="var(--accent)" stroke-width="2" vector-effect="non-scaling-stroke"/>
    </svg>
    <div style="font-size:11.5px;color:var(--faint);margin-bottom:20px">Growth of $10,000, log scale. ${M[startIdx].slice(0,4)} to ${M[endIdx].slice(0,4)}.</div>

    <table class="tgt" style="margin-bottom:16px">
      <tr><th style="text-align:left">&nbsp;</th><th style="text-align:right">Ended with</th><th style="text-align:right">Per year</th><th style="text-align:right">Worst drop</th></tr>
      <tr><td><b>Your mix</b></td><td class="num" style="text-align:right"><b>${money(START$*mine.val)}</b></td><td class="num" style="text-align:right"><b>${pct(cagr)}</b></td><td class="num" style="text-align:right"><b>${pct(mine.maxDD)}</b></td></tr>
      ${Object.entries(bench).map(([n,b]) => `<tr><td style="color:var(--muted)">${n}</td><td class="num" style="text-align:right;color:var(--muted)">${money(START$*b.val)}</td><td class="num" style="text-align:right;color:var(--muted)">${pct(btCagr(b.val,b.curve.length))}</td><td class="num" style="text-align:right;color:var(--muted)">${pct(b.maxDD)}</td></tr>`).join('')}
      <tr><td style="color:var(--muted)">Your mix, never rebalanced</td><td class="num" style="text-align:right;color:var(--muted)">${money(START$*noRebal.val)}</td><td class="num" style="text-align:right;color:var(--muted)">${pct(btCagr(noRebal.val,noRebal.curve.length))}</td><td class="num" style="text-align:right;color:var(--muted)">${pct(noRebal.maxDD)}</td></tr>
    </table>

    ${worst ? `<div style="font-size:13.5px;line-height:1.8;margin-bottom:16px">
      Worst calendar year was <b>${worst.y}</b> at <span class="over num" style="font-weight:600">${pct(worst.r)}</span>. On ${money(100000)} that's ${money(-worst.r*100000)} gone in twelve months.
      Best was <b>${best.y}</b> at <span class="under num" style="font-weight:600">+${pct(best.r)}</span>.
      ${yv.length} full years, ${downYears} of them negative.
    </div>` : ''}

    <div class="res-note"><b>This is history, not a forecast.</b> Index returns with no fund fees, spreads, or taxes taken out, so a real portfolio would have done somewhat worse. The past ${(nMonths/12).toFixed(0)} years happened once and won't repeat.
    ${unknown > 0.5 ? `<br><br>About ${Math.round(unknown)}% of your target sits in custom sleeves with no long history here, so the mix above was rescaled to the classes that do have data.` : ''}
    ${(w.INTL > 0 && (targetsRaw().EM > 0.5 || targetsRaw().INTLSCV > 0.5)) ? `<br><br>Emerging markets and international small value have no free long-run series, so they're backtested as developed international. Real EM has been more volatile than that.` : ''}
    <br><br>Sources: <a href="https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html" target="_blank" rel="noopener" style="color:var(--accent)">Ken French Data Library</a> for stocks, <a href="https://fred.stlouisfed.org/series/GS10" target="_blank" rel="noopener" style="color:var(--accent)">FRED</a> for the 10-year Treasury and CPI. Bonds are modelled as a par 10-year Treasury repriced monthly, which is a proxy for a real bond fund, not a match.</div>`;
}

function btSet(k, v){ BT[k] = v; renderBacktest(); }

(async function loadReturns(){
  try{
    const res = await fetch('returns.json', {cache:'no-store'});
    if(!res.ok) throw 0;
    const d = await res.json();
    if(!d || !Array.isArray(d.months) || !d.series) throw 0;
    RET = d;
  }catch(e){ RET = 'missing'; }
  try{ renderBacktest(); }catch(e){}
})();


/* re-render whenever the rest of the page re-renders */
const _renderAll = window.renderAll;
if(typeof _renderAll === 'function'){
  window.renderAll = function(){
    const out = _renderAll.apply(this, arguments);
    try{ renderBacktest(); }catch(e){}
    return out;
  };
}
window.btSet = btSet;
try{ renderBacktest(); }catch(e){}
})();

